services:
  mysql:
    container_name: msa-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD : root
    ports:
      - "13306:3306"
    volumes:
      - ./docker/docker-sql/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - msa-network

  redis:
    container_name: msa-redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "18001:8001"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge

