services:
  auth_db:
    image: mysql:latest
    container_name: auth_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATEBASE: auth_db
    ports:
      - 13306:3306
    networks:
      - msa-network


  order_db:
    image: mysql:latest
    container_name: order_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATEBASE: order_db
    ports:
      - 13307:3306
    networks:
      - msa-network

  product_db:
    image: mysql:latest
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATEBASE: product_db
    ports:
      - 13308:3306
    networks:
      - msa-network

  redis:
    container_name: msa-redis
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "18001:8001"
    networks:
      - msa-network

networks:
  msa-network:
    name: msa-network
    driver: bridge

