eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use_version_always: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: false

  data:
    redis:
      host: localhost
      port: 6379