server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/products/**
      discovery:
        locator:
          enabled: true


